services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    # Enable memory overcommit to prevent save/replication failures
    # If this doesn't work, run: sudo sysctl vm.overcommit_memory=1
    sysctls:
      - net.core.somaxconn=511
    # Uncomment if you have permission issues with sysctls:
    # privileged: true
  mongo:
    image: mongo
    volumes:
      - ./tmp-test-server-database/:/data/db
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null 
  server:
    image: node:20
    working_dir: /mnt
    volumes:
      - ./:/mnt
    command: ./utils/continueTestServer.sh
    environment:
      - STEAM_API_KEY
      - STEAM_ID
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    #network_mode: "host"
    ports:
      - 21025:21025
      - 21026:21026